import type { SupabaseClient } from "@supabase/supabase-js";

import type { AgentRuntimeContext } from "@/lib/application/agents/build-agent-runtime-context";
import type { AgentCapabilityExecutionResult } from "@/lib/application/agents/agent-capabilities";
import {
  createExecutionQueueItem,
} from "@/lib/application/execution-queue/create-execution-queue-item";

const FOLLOW_UP_WORK_AGENT_NAME = "Operations Agent";
const FOLLOW_UP_WORK_TITLE = "Continue execution after human approval";
const FOLLOW_UP_WORK_REASON =
  "follow-up work generated by capability";

export type WorkGenerationResult = {
  created_work_items: string[];
  created_queue_items: string[];
  skipped_duplicates: Array<{
    type: "work_item" | "queue_item";
    id: string;
    reason: string;
  }>;
};

type GenerateFollowUpWorkInput = {
  supabase: SupabaseClient;
  organizationId: string;
  parentWorkItemId: string;
  agentExecutionId: string;
  capabilityId: string;
  capabilityResult: AgentCapabilityExecutionResult;
  runtimeContext: AgentRuntimeContext;
  processedAt?: string;
};

type WorkItemRow = {
  id: string;
  metadata?: Record<string, unknown> | null;
};

type AgentRow = {
  id: string;
  name: string;
  config: Record<string, unknown> | null;
};

type AgentDecisionRow = {
  id: string;
};

export async function generateFollowUpWork({
  supabase,
  organizationId,
  parentWorkItemId,
  agentExecutionId,
  capabilityId,
  capabilityResult,
  runtimeContext,
  processedAt = new Date().toISOString(),
}: GenerateFollowUpWorkInput): Promise<WorkGenerationResult> {
  const result: WorkGenerationResult = {
    created_work_items: [],
    created_queue_items: [],
    skipped_duplicates: [],
  };

  if (!canGenerateFollowUpWork({ capabilityId, runtimeContext })) {
    return result;
  }

  const existingWorkItem = await findExistingFollowUpWorkItem({
    supabase,
    organizationId,
    parentWorkItemId,
    capabilityId,
  });
  const agent = await loadOperationsAgent({ supabase, organizationId });

  let workItemId = existingWorkItem?.id ?? null;

  if (existingWorkItem) {
    result.skipped_duplicates.push({
      type: "work_item",
      id: existingWorkItem.id,
      reason: "follow_up_work_exists_for_parent_and_capability",
    });
  } else {
    const workItem = await createFollowUpWorkItem({
      supabase,
      organizationId,
      parentWorkItemId,
      agentExecutionId,
      capabilityResult,
      runtimeContext,
      agent,
      processedAt,
    });

    workItemId = workItem.id;
    result.created_work_items.push(workItem.id);
  }

  if (!workItemId) {
    return result;
  }

  const decision = await createFollowUpWorkDecision({
    supabase,
    organizationId,
    parentWorkItemId,
    agentExecutionId,
    agent,
    capabilityResult,
    result,
    processedAt,
  });

  const queueItem = await createExecutionQueueItem({
    supabase,
    organizationId,
    workItemId,
    sourceDecisionId: decision.id,
    assignedAgentId: agent?.id ?? null,
    assignedAgentName: FOLLOW_UP_WORK_AGENT_NAME,
    priority: "high",
    queueReason: FOLLOW_UP_WORK_REASON,
    nextAction: capabilityResult.recommended_next_action,
  });

  if (result.created_work_items.includes(workItemId)) {
    result.created_queue_items.push(queueItem.id);
  } else {
    result.skipped_duplicates.push({
      type: "queue_item",
      id: queueItem.id,
      reason: "open_queue_item_exists_for_follow_up_work",
    });
  }

  await updateFollowUpWorkDecisionCreatedIds({
    supabase,
    organizationId,
    decisionId: decision.id,
    parentWorkItemId,
    capabilityResult,
    result,
    processedAt,
  });

  return result;
}

function canGenerateFollowUpWork({
  capabilityId,
  runtimeContext,
}: {
  capabilityId: string;
  runtimeContext: AgentRuntimeContext;
}) {
  return (
    capabilityId === "summarize_review_decision" &&
    runtimeContext.assigned_agent.name === FOLLOW_UP_WORK_AGENT_NAME
  );
}

async function findExistingFollowUpWorkItem({
  supabase,
  organizationId,
  parentWorkItemId,
  capabilityId,
}: {
  supabase: SupabaseClient;
  organizationId: string;
  parentWorkItemId: string;
  capabilityId: string;
}) {
  const { data, error } = await supabase
    .from("work_items")
    .select("id, metadata")
    .eq("organization_id", organizationId)
    .eq("type", "follow_up")
    .eq("source_type", "capability");

  if (error) {
    throw error;
  }

  return ((data ?? []) as WorkItemRow[]).find((workItem) => {
    const metadata = workItem.metadata ?? {};

    return (
      metadata.source === "capability_work_generation" &&
      metadata.parent_work_item_id === parentWorkItemId &&
      metadata.capability_id === capabilityId
    );
  });
}

async function loadOperationsAgent({
  supabase,
  organizationId,
}: {
  supabase: SupabaseClient;
  organizationId: string;
}) {
  const { data, error } = await supabase
    .from("agents")
    .select("id, name, config")
    .eq("organization_id", organizationId)
    .eq("name", FOLLOW_UP_WORK_AGENT_NAME)
    .maybeSingle<AgentRow>();

  if (error) {
    throw error;
  }

  return data;
}

async function createFollowUpWorkItem({
  supabase,
  organizationId,
  parentWorkItemId,
  agentExecutionId,
  capabilityResult,
  runtimeContext,
  agent,
  processedAt,
}: {
  supabase: SupabaseClient;
  organizationId: string;
  parentWorkItemId: string;
  agentExecutionId: string;
  capabilityResult: AgentCapabilityExecutionResult;
  runtimeContext: AgentRuntimeContext;
  agent: AgentRow | null;
  processedAt: string;
}) {
  const { data, error } = await supabase
    .from("work_items")
    .insert({
      organization_id: organizationId,
      title: FOLLOW_UP_WORK_TITLE,
      description:
        "Follow-up work created after an approved human review so Operations can continue from a queued work item.",
      type: "follow_up",
      status: "queued",
      priority: "high",
      source_type: "capability",
      source_id: agentExecutionId,
      lead_id: runtimeContext.lead?.id ?? null,
      parent_work_item_id: parentWorkItemId,
      owner_type: "ai",
      owner_agent_id: agent?.id ?? null,
      owner_agent_name: FOLLOW_UP_WORK_AGENT_NAME,
      owner_agent_role: getAgentRole(agent),
      ownership_status: "assigned",
      last_owner_change_at: processedAt,
      last_owner_change_reason: FOLLOW_UP_WORK_REASON,
      metadata: {
        source: "capability_work_generation",
        phase: 23,
        parent_work_item_id: parentWorkItemId,
        agent_execution_id: agentExecutionId,
        capability_id: capabilityResult.capability_id,
        capability_name: capabilityResult.capability_name,
        recommended_next_action:
          capabilityResult.recommended_next_action,
        generated_by_agent_name: runtimeContext.assigned_agent.name,
        assigned_agent_name: FOLLOW_UP_WORK_AGENT_NAME,
        openai_called: false,
      },
      created_at: processedAt,
      updated_at: processedAt,
    })
    .select("id, metadata")
    .single<WorkItemRow>();

  if (error) {
    throw error;
  }

  return data;
}

async function createFollowUpWorkDecision({
  supabase,
  organizationId,
  parentWorkItemId,
  agentExecutionId,
  agent,
  capabilityResult,
  result,
  processedAt,
}: {
  supabase: SupabaseClient;
  organizationId: string;
  parentWorkItemId: string;
  agentExecutionId: string;
  agent: AgentRow | null;
  capabilityResult: AgentCapabilityExecutionResult;
  result: WorkGenerationResult;
  processedAt: string;
}) {
  const outcome = buildDecisionOutcome({
    parentWorkItemId,
    capabilityResult,
    result,
    processedAt,
  });

  const { data, error } = await supabase
    .from("agent_decisions")
    .insert({
      organization_id: organizationId,
      agent_execution_id: agentExecutionId,
      agent_id: agent?.id ?? null,
      work_item_id: parentWorkItemId,
      decision_type: "follow_up_work_generated",
      decision: {
        outcome,
      },
      rationale:
        "Operations Agent created follow-up work after human approval.",
      confidence: 1,
      metadata: {
        source: "work_generation",
        phase: 23,
        ...outcome,
        openai_called: false,
      },
      created_at: processedAt,
    })
    .select("id")
    .single<AgentDecisionRow>();

  if (error) {
    throw error;
  }

  return data;
}

async function updateFollowUpWorkDecisionCreatedIds({
  supabase,
  organizationId,
  decisionId,
  parentWorkItemId,
  capabilityResult,
  result,
  processedAt,
}: {
  supabase: SupabaseClient;
  organizationId: string;
  decisionId: string;
  parentWorkItemId: string;
  capabilityResult: AgentCapabilityExecutionResult;
  result: WorkGenerationResult;
  processedAt: string;
}) {
  const outcome = buildDecisionOutcome({
    parentWorkItemId,
    capabilityResult,
    result,
    processedAt,
  });

  const { error } = await supabase
    .from("agent_decisions")
    .update({
      decision: {
        outcome,
      },
      metadata: {
        source: "work_generation",
        phase: 23,
        ...outcome,
        openai_called: false,
      },
    })
    .eq("id", decisionId)
    .eq("organization_id", organizationId);

  if (error) {
    throw error;
  }
}

function buildDecisionOutcome({
  parentWorkItemId,
  capabilityResult,
  result,
  processedAt,
}: {
  parentWorkItemId: string;
  capabilityResult: AgentCapabilityExecutionResult;
  result: WorkGenerationResult;
  processedAt: string;
}) {
  return {
    parent_work_item_id: parentWorkItemId,
    created_work_item_ids: result.created_work_items,
    created_queue_item_ids: result.created_queue_items,
    capability_id: capabilityResult.capability_id,
    capability_name: capabilityResult.capability_name,
    reason:
      "Operations Agent created follow-up work after human approval.",
    skipped_duplicates: result.skipped_duplicates,
    processed_at: processedAt,
  };
}

function getAgentRole(agent: AgentRow | null) {
  const role = agent?.config?.role;

  return typeof role === "string" ? role : null;
}
